### ISSUE TITLE
remark-caption : nocheck for first paragraph child of the legend candidate

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#101]
Error is here : https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-captions/src/index.js#L112

error happend on : 

```
    ```csharp
    public async Task VotreTache(){
   
       await QuelquechoseDeLongQuiNeTouchePasALaGui().ConfigureAwait(continueOnCapturedContext:false);
       await QuelquechoseDeLongQuiToucheALaGui().ConfigureAwait(continueOnCapturedContext:true);
    }

    private async void DoClick(object sender, EventArg args){ //votre délégué pour le click
        this.Button1.Text = "Before the task"
        await VotreTache().ConfigureAwait(continueOnCapturedContext:true);//on continue sur la GUI
        this.Button1.Text = "After the task"
    }
    ```

    *[GUI]: Graphical UserInterface
```

the error : 
```
TypeError: l.value is undefined[En savoir plus]  bundle.js:3528:1247
	externLegendVisitorCreator/< https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3528:1247
	u https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3391:103
	e https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3391:245
	u https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3391:138
	visit https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3391:316
	plugin/</< https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3528:260
	forEach self-hosted:252:13
	plugin/< https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3528:218
	l https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3334:706
	n https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3334:207
	r https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3334:856
	u https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3334:895
	l https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3334:828
	n https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3334:207
	n https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3334:418
	i https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3367:1851
	s https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3367:1943
	u https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3367:2020
	rehypeCompiler/< https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3609:3581
	stringToHTML/< https://zestedesavoir.github.io/zmarkdown/public/bundle.js:3609:4031
	update
```

**Comment by AmarOk1412** [comment]
@artragis c'est toujours le cas cette issue ?
