### ISSUE TITLE
implement zds extension: <del>

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#11]

**Comment by vhf** [comment]
Cf. `kbd` extension

**Comment by artragis** [comment]
étant donné que ton ticket n'a pas de description et qu'on a "cf kbd" je ne sais pas : est-ce toujours d'actualité?

si oui, assigne-le moi stp.

**Comment by vhf** [comment]
`kbd`: https://github.com/zestedesavoir/zmarkdown/tree/master/packages/kbd

`<del>`: [from](https://github.com/zestedesavoir/zmarkdown/blob/master/test/fixtures/zds/extensions/delext.txt) [to](https://github.com/zestedesavoir/zmarkdown/blob/master/test/fixtures/zds/extensions/delext.html)
