### ISSUE TITLE
rebber-images : includegraphics -> image

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#119]
According to @Karnaj the `image` node should be translated into `\\image{url}` and `\\image{url}[caption]` when it is useful.

I don't know if we should modify the rebber core as `\\includeGraphics` is far more standard than ``\\image` or use an "override" configuration in the `zmarkdown` package.

**Comment by vhf** [comment]
I'd keep `\includeGraphics` as default macro and override it with our custom one.
