### ISSUE TITLE
remark-disable-tokenizers: link to possible tokenisers to turn off

### ISSUE THREAD

**Issue by wooorm** [zestedesavoir/zmarkdown#125]
Current [readme](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-disable-tokenizers) doesn’t explain which tokenisers can be turned off. I guess zmarkdown is adding many more, but it’d be good to link to the default ones!

**Comment by vhf** [comment]
I couldn't find a list of them in remark's repo, is there one? I'd like to avoid generating it because although it's easy to do, it might end up out of sync with remark-parse. :)

**Comment by wooorm** [comment]
True, I’ll try and create a automatically maintained [list in the readme](https://github.com/wooorm/remark/tree/master/packages/remark-parse#parserblocktokenizers) later.

**Comment by eccentric-j** [comment]
Hey there the link in the readme to the list of tokenizers is not working and I'm having trouble locating where that information is located. Any hints?

**Comment by StaloneLab** [comment]
Hello @eccentric-j ,

First, please note that we do not support remark versions greater than or equal to 13 for any of the plugins included in this repo. For more information about this, see #416 .

That being said, if you are using remark < 13, the list of default tokenizers can be found [here](https://github.com/remarkjs/remark/tree/12.0.1/packages/remark-parse#parserblockmethods). I will take care of updating the link included in the README, thanks for your report!

In order not to bother anymore the other contributors to this issue (which dates back 2017), I'm locking this conversion, but please feel free to open a new issue should you need more details.
