### ISSUE TITLE
IDL descriptions for mdast extensions

### ISSUE THREAD

**Issue by wooorm** [zestedesavoir/zmarkdown#126]
I suggest documenting in each project that adds new mdast nodes how they work, in some way similar to the [mdast spec](https://github.com/syntax-tree/mdast#ast).

**Comment by vhf** [comment]
Progress:

* [ ] [`remark-abbr`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-abbr)
* [ ] [`remark-align`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-align)
* [ ] [`remark-captions`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-captions)
* [ ] [`remark-comments`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-comments)
* [ ] [`remark-custom-blocks`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-custom-blocks)
* [ ] [`remark-disable-tokenizers`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-disable-tokenizers)
* [ ] [`remark-emoticons`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-emoticons)
* [ ] [`remark-escape-escaped`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-escape-escaped)
* [ ] [`remark-fix-guillemets`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-fix-guillemets)
* [ ] [`remark-grid-tables`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-grid-tables)
* [x] [`remark-heading-shift`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-heading-shift)
* [x] [`remark-heading-trailing-spaces`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-heading-trailing-spaces)
* [ ] [`remark-iframes`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-iframes)
* [x] [`remark-kbd`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-kbd)
* [ ] [`remark-numbered-footnotes`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-numbered-footnotes)
* [x] [`remark-ping`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-ping)
* [x] [`remark-sub-super`](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-sub-super)

**Comment by artragis** [comment]
Ok for remark-captions https://github.com/zestedesavoir/zmarkdown/tree/master/packages/remark-captions#syntax

**Comment by artragis** [comment]
Ok for remark-iframe

**Comment by artragis** [comment]
@vhf this one should be fixed now?
