### ISSUE TITLE
remark-ping: docs mention zestedesavoir, not how to set it up?

### ISSUE THREAD

**Issue by wooorm** [zestedesavoir/zmarkdown#131]
I suggest the docs show how to configure `remarkPingZds` for your own site!

**Comment by artragis** [comment]
I take this.

**Comment by vhf** [comment]
I guess the doc is out of sync with the code. This plug-in isn't specific at all, it doesn't depend on our setup.

Improving the doc and adding examples is always good though, obviously

**Comment by vhf** [comment]
Ok so let's recap:

```js
.use('remark-ping', {
  pingUsername (username) {
    return doWhateverReturnTrueIfUsernameCanBePinged(username)
  },
  userURL (username) {
    return `https://github.com/${username}`
  },
})
```

:)

**Comment by wooorm** [comment]
Is the return value in `pingUsername` used?

**Comment by vhf** [comment]
Nope. It should return something truthy, my example is unsuitable for a README I only quickly wrote something here to show how generic it is. :)

`pingUsername` should return a bool, I just noticed while writing this example that truthy isn't good enough. I'll change it to a `true` check instead.

**Comment by vhf** [comment]
Done via 090342b .

I didn't publish, this will wait for @artragis ' doc fixes.
