### ISSUE TITLE
A lot of junk seems to be included in the zmarkdown package

### ISSUE THREAD

**Issue by motet-a** [zestedesavoir/zmarkdown#135]
How to reproduce:

```sh
$ mkdir some_temporary_dir
$ cd some_temporary_dir
$ npm init
<press Enter many times>
$ npm i --save zmarkdown
$ ls -R -1 node_modules/zmarkdown | wc -l
474
$ du -sh node_modules/zmarkdown        
4.0M	node_modules/zmarkdown
```

There are more than 400 files and it weights 4 MB.

I think the package size can be significantly reduced using the [`files` field in the package.json](https://docs.npmjs.com/files/package.json#files) or a `.npmignore`.

**Comment by vhf** [comment]
`zmarkdown` is pretty much a private package providing ZdS' custom-tailored configs, APIs and demos.

What you describe as _junk_ is actually tests and web bundles with huge source maps.

You shouldn't use `zmarkdown` as it doesn't provide any actual functionality, it's only there to tie some plugins together with our custom config.

**Comment by motet-a** [comment]
OK, thanks! I thought it was a regular npm package.

**Comment by vhf** [comment]
Thanks for the report.  :+1:

I'll add a disclaimer sometime in the future. There's no README in the `zmarkdown` package atm, it'd be a good idea to add a note in there explaining that we won't accept bug reports or feature requests that are not related to ZdS, and saying that anyone is obviously welcome to fork and republish if they want to adjust it to their need.
