### ISSUE TITLE
rebber: some parser mistakes

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#137]
From [this attempt](https://github.com/zestedesavoir/latex-template/issues/63), I notice some mistakes in the parsing process:

- [x] ~~Parser bug: `\addSecret` → `\addSpoiler`~~ (see below)
- [x] Parser bug: `\includeGraphics`→ `\includegraphics` (this is a LaTeX base command, not a custom one, so it is lowercase). See #119 anyway, because `\image` is better ;)
- [x] Parser bug (?): insecable space (`U+202F`) before each `:` (I don't know if it is the parser that add these, anyway using a unicode-supported flavor of TeX may also be a solution, as `XeTeX`). Also, I don't know if you force the replacement from  `'` to typographic one, but TeX prefers to deal with that on its own.
- [x] Parser bug: `\captionof{path}` → `\captionof{figure}{path}`
- [x] Parser bug: some `##` were left intact in the document (but were escaped correctly, so it didn't cause any issue :) )
- [x] Parser bug: ~~what is `\ref{}` supposed to be translated from ? Footnotes or something else ? (because if there is `\ref{}`, there should be `\label{}`)~~ Ok, I get it. Every time you have a footnote, you put `\ref{t}\footnote{\label{t} xxx}`, which is not coorrect. That should be `\footnotetext[number]{\label{t} xxx}` (where number is the number displayed) and `\ref{t}` where there is a `[^t]` (actually, `\textsuperscript{\ref{t}}`). Also, you can prefix the labels (i.e. `\ref{footnote:t}`) to avoid confusion if you want :)
- [x] You are not using the custom title commands.

and, due to this experiment,

- [x] `\addSpoiler{}` → `\begin{Spoiler}` (spoilers are now defined in an environement, which can support many things: images, quotation and ... Code, of course)
- [x] `\begin{codeBlock}`→ `\begin{CodeBlock}` (because if we have defined rules, is to follow them ^^)

There is also ~~one error that we need to work on (code in spoilers, https://github.com/zestedesavoir/latex-template/issues/64)~~ (*fixed*) and one that is due to LaTeX: when using

```latex
\includegraphics{images/25d8a05f-eefa-41d8-879f-be632c59bf31.png.960x960_q85.jpg}
```

... LaTeX thinks that the extension of the image is `.png.960x960_q85.jpg`, which it does not recognize, of course. I don't know yet what to do against this stupid issue.

**Comment by artragis** [comment]
>You are not using the custom title commands.

this is quite complexe to use this one, moreover, as it is not standard, it must be pushed into zmarkdown configuration, not in rebber core.

> \\includegraphics

the strangest thing is that we do import images and we do not have the .png.bidule.jpg

**Comment by artragis** [comment]
>  Every time you have a footnote, you put `\ref{t}\footnote{\label{t} xxx}`

logically what we do is : 

- on footnoteDef, we put `\footnote{\label{t} xxx}`
- on footnoteRef, we put `\ref{t}`
- on footnote (definition & reference at the same time), we put what you said

what we need is wrap `\ref between text-supper`.

**Comment by pierre-24** [comment]
> on footnoteDef, we put \footnote{\label{t} xxx}

Yes but `\footnote{}` comes with a superscript as well, so you need to use `\footnotetext{}` instead :)

> this is quite complexe to use this one, moreover, as it is not standard, it must be pushed into zmarkdown configuration, not in rebber core.

As you wish :) (but we thought using `#` = level one, `##` = level two and so all would be easier for you, in fact)

>  the strangest thing is that we do import images and we do not have the .png.bidule.jpg

It is coming from the gallery in ZDS: every time you include an image which was larger than 960px large, it is dimensioned and get this weird name. You just copied that into `images/` ?

**Comment by motet-a** [comment]
> Parser bug (?): insecable space (U+202F) before each : (I don't know if it is the parser that add these, anyway using a unicode-supported flavor of TeX may also be a solution, as XeTeX). Also, I don't know if you force the replacement from ' to typographic one, but TeX prefers to deal with that on its own.

I don't think this [non-breaking space insertion](https://github.com/zestedesavoir/zmarkdown/tree/master/packages/typographic-colon) is a bug. However, the unicode support is a whole different concern. Is it possible to prefix the LaTeX files with `\usepackage[utf8]{inputenc}`?

**Comment by pierre-24** [comment]
Sadly, `inputenc` is already included, and it only treat partially the unicode. And when we say that XeTeX is able to handle unicode, it only means that we can include chinese characters if we want.

LaTeX was (and is still) designed to take care of typographic stuffs on its own, and was not designed to handle proper typography made with unicode characters (and is still not, from my tests). For example, LaTeX will replace the "normal" apostrophe with the typographic one by default, and an already included typographic apostrophe will look bad because it is not taken care of properly. LaTeX also add insecable spaces on its own (and based on the language), and once again, already included ones are weirdly rendered. So, if it is possible to deactive this package for rebber, I think it would be better, because I'm pretty sure that most of the things that packages does, LaTeX does it as well (and if not, of course, we can still keep some stuffs from it).

**Comment by pierre-24** [comment]
Just to mention two changes induced by https://github.com/zestedesavoir/latex-template/pull/65:

+ `\addSpoiler{}` → `\begin{Spoiler}` (spoilers are now defined in an environement, which can support many things: images, quotation and ... Code, of course)
+ `\begin{codeBlock}`→ `\begin{CodeBlock}` (because if we have defined rules, is to follow them ^^)

**Comment by vhf** [comment]
Regarding the footnotes, please provide a full example.

I tried to parse the following explanation:

> - [ ] Parser bug: ~~what is `\ref{}` supposed to be translated from ? Footnotes or something else ? (because if there is `\ref{}`, there should be `\label{}`)~~ Ok, I get it. Every time you have a footnote, you put `\ref{t}\footnote{\label{t} xxx}`, which is not coorrect. That should be `\footnotetext[number]{\label{t} xxx}` (where number is the number displayed) and `\ref{t}` where there is a `[^t]` (actually, `\textsuperscript{\ref{t}}`). Also, you can prefix the labels (i.e. `\ref{footnote:t}`) to avoid confusion if you want :)

I really couldn't.

**Comment by pierre-24** [comment]
So the following code in markdown

```md
This a sentence[^foo1] with nice footnotes[^foo2], but one repeated[^foo1].

[^foo1]: A footnote
[^foo2]: A second one
```

Should looks in LaTeX like

```latex
% text with \textsuperscript{\ref{t}}
This a sentence\textsuperscript{\ref{foo1}} with nice footnotes\textsuperscript{\ref{foo2}}, but one repeated\textsuperscript{\ref{foo1}}.

% footnote text definition with \footnotetext[number]{\label{t} xxx}
\footnotetext[1]{\label{foo1} A footnote}
\footnotetext[2]{\label{foo2} A second one}
```

That may be easier presented like that :)
