### ISSUE TITLE
[rebber] Quotations

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#152]
The following MD code

```md
> Rien ne se perd, rien ne se crée, tout se transforme
Source: Antoine A. Lavoisier
```

Is translated

```latex
\begin{Quotation}{Antoine A. Lavoisier}
Rien ne se perd, rien ne se crée, tout se transforme
\end{Quotation}
```

... But it [should be square brackets](https://github.com/zestedesavoir/latex-template/blob/master/documentation.md#quotes) (OK, our bad, the documentation is not clear enough, we assume that a optional parameter is always `[]`, but it is not evident for non-LaTeX users):

```latex
\begin{Quotation}[Antoine A. Lavoisier]
Rien ne se perd, rien ne se crée, tout se transforme
\end{Quotation}
```

**Comment by artragis** [comment]
ok. i fix it this afternoon
