### ISSUE TITLE
zmarkdown: add a setting to postfix footnote anchors/refs with a random shortid

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#168]
When two posts on the same page (or a comment on an article and the article) use footnotes, we end up with conflicting anchors.

IMO a random thing is good enough for all posts/comments because linking to a footnote def/ref in a comment doesn't make much sense.

**Comment by vhf** [comment]
Ideally this random thing setting should be overridable, that way we'll be able to handle footnotes conflicts arising from displaying several "extracts" on one page.

**Comment by motet-a** [comment]
*Related to https://zestedesavoir.com/forums/sujet/9280/references-non-uniques-dans-un-sujet/*.

**Comment by Ymox** [comment]
Rather than a random thing, why not use the post ID along with an incremented number?

**Comment by motet-a** [comment]
@Ymox You’re right but a random ID looks easier to implement to me. We don’t have to change the public interface exposed by zmarkdown in order to accept that “post ID” namespace.
