### ISSUE TITLE
implement zds extension: emoticons

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#17]
* original implementation: https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/zmarkdown/extensions/emoticons.py
* tests:
    * https://github.com/zestedesavoir/zmarkdown/blob/master/test/fixtures/zds/extensions/emoticons.txt
    * https://github.com/zestedesavoir/zmarkdown/blob/master/test/fixtures/zds/extensions/emoticons.html

**Comment by artragis** [comment]
2beclosed @vhf

**Comment by artragis** [comment]
en fait je peux le faire, dsl pour le bruit
