### ISSUE TITLE
Activate remark-images-download in zmarkdown/index.js

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zmarkdown#174]
For now, remote images are not downloaded for `rebber`. We need to activate `remark-images-download` in https://github.com/zestedesavoir/zmarkdown/blob/master/packages/zmarkdown/index.js

**Comment by vhf** [comment]
Done via 69aefb1e7fd5c5f5f4e870997f20ef39d4499fe3 . I had to rewrite a few things while doing this so don't look at this commit. `remark-images-download` was also totally broken, see #183 for full resolution. (I had to come up with a not-so-fun hack to tie together callbacks+events+streams into promises that get sorted before being executed sequentially.)
