### ISSUE TITLE
include luafiles in deployment

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#175]
Now htat we use lualatex @heziode added some lua files into the template project. We need to import them in the zmd install script.

**Comment by Heziode** [comment]
You are faster than the [PR](https://github.com/zestedesavoir/latex-template/pull/76). It has not yet been accepting.

The repo will need submodules for working. So, you will probably have to use a procedure like `git submodule update --init --recursive` for getting submodules.

**Comment by artragis** [comment]
yes but as we are not as fast as in the beginning, I prefer posting the issue now that I remember it.

**Comment by pierre-24** [comment]
PR has been accepted :)

**Comment by artragis** [comment]
we'll close this issue as it is handled in zds-site now.
