### ISSUE TITLE
Update zmd with new latex-template features

### ISSUE THREAD

**Issue by Heziode** [zestedesavoir/zmarkdown#176]
This issue is for preparing zmd for release.

What has to be done:
- [ ] include luafiles in deployment (#175)
- [x] Update inline code

What else ?

**Comment by artragis** [comment]
update inline code?

you can also add the new `\iframe` command that can be used.

**Comment by Heziode** [comment]
@artragis 
Inline use a [costom command now](https://github.com/zestedesavoir/latex-template/blob/master/documentation.md#inline-source-code)
