### ISSUE TITLE
[Suggestion] Change the result of special blocks

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zmarkdown#184]
Today, the special blocks are somewhere between [that kind of alert](http://docdock.netlify.com/shortcodes/alert/) and [this type of information](http://docdock.netlify.com/shortcodes/notice/), in the way that they do not have a header but the icon is imposed by the type of block.

The proposition is to add [this type of block](http://docdock.netlify.com/shortcodes/panel/), which will have these advantages, compared to existing:

- Ability to have "neutral" blocks.
- Ability to have a custom title.
- Ability to add a long text in a block without all the page being colored (really usefull with neutral blocks).
- Normally easy to add a type of block.

---------------------------

Topic's answers :

It would be a way to add the already mentionned blocks of type « Demonstration », « Theoreme », « Definition », numbered if possible.
The personalized blocks would have a limited choice of themes (at least : the existings + « neutral »), the title would be totally customisable.

Subject : https://zestedesavoir.com/forums/sujet/9492/suggestion-assouplir-la-gestion-des-blocs-speciaux/
*From zestedesavoir/zds-site#4716*
*Sent from Zeste de Savoir*

**Comment by vhf** [comment]
Please come up with syntax suggestions.

**Comment by nils-van-zuijlen** [comment]
I would suggest
```
[ Title (custom or not) | style ]
| content
| another line of content
```
Style may be omitted, falls back to neutral or default for the title to preserve backward compatibility.

For example :
```
[ Information ]
| some information

[ Please be aware that | warning ]
| this may cause troubles
```

**Comment by artragis** [comment]
with double `[]` I think : 

```
[[Information]]
| some information


[[ Please be aware that | warning ]]
|
```

**Comment by nils-van-zuijlen** [comment]
> To me prefixing would make more sense than postfixing.
>
> ```[[warning|Be careful: I'm a crazy horse]]```

Yes, it may, and also it will help much more to preserve backward compatibility as the current blocks are :
```
[[information]]
| 

[[question]]
| 

[[attention]]
| 

[[erreur]]
| 

[[secret]]
| 
```

So, the new blocks would be :
```
[[neutre|Custom title]]
| 

[[information|Another custom title with the info style]]
| 
```

**Comment by vhf** [comment]
Done on our side.

It now needs some latex template work:

* `neutral` box: https://github.com/zestedesavoir/latex-template/blob/master/zmdocument.cls#L109-L144
* titles support for all box types

**Comment by Heziode** [comment]
@vhf As soon as I find a moment I do that ;)

**Comment by Heziode** [comment]
[latex-template#82](https://github.com/zestedesavoir/latex-template/pull/82).

Example:
![test](https://user-images.githubusercontent.com/16735076/36067907-a5e5956e-0ec8-11e8-8e92-395ad54a239d.png)
