### ISSUE TITLE
Line numbers do not appear in code blocks

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#187]
When I enter a code block, line number does not appear when using zmardown server

![screenshot-2018-1-19 neque harum odio facere cupiditate billets zeste de savoir](https://user-images.githubusercontent.com/1523653/35161857-bed9cc72-fd41-11e7-980f-6c355f873177.png)

**Comment by vhf** [comment]
I suggest a CSS solution such as https://codepen.io/elomatreb/pen/hbgxp instead of having line numbers in the HTML source.
