### ISSUE TITLE
remark-download-images is not used for html, hence epub can't be built

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#189]
Can we have the ability to set up the "image_download_dir" for html rendering in zmarkdown. This is important for epub generation.

**Comment by vhf** [comment]
I'd rather have a separate endpoint for this. Something like `/epub`. Ideally we would simply reuse the image folder we used for PDF generation though.

**Comment by artragis** [comment]
I don't have any insurance the pdf will be built before epub.

**Comment by vhf** [comment]
https://github.com/zestedesavoir/zmarkdown/blob/a7d8f1c3f6b0bbfbda024cb8cd566e719facb395/packages/zmarkdown/README.md#epub---markdown-to-html

Fixed via a7d8f1c3f6b0bbfbda024cb8cd566e719facb395
