### ISSUE TITLE
remark-download-image and / starting url

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#190]
Zeste De Savoir generates url that starts with / when dealing with gallery images.

The problem is that remark-download-images interprets them as absolute path and therefore doesn't download them.

We need to say "if the url starts with /, prepend https://zestedesavoir.com". I vote for "base_url" parameter to be in sync with html meta.

**Comment by vhf** [comment]
These images already being available locally I don't see the point of downloading them again. What about prefixing their path with a user provided string (path to their local location)?

**Comment by vhf** [comment]
An even better option might be to `cp` local files to the same destination folder as the downloaded ones by providing the absolute local path and joining it to the absolute URL image path.

**Comment by artragis** [comment]
> These images already being available locally I don't see the point of downloading them again. What about prefixing their path with a user provided string (path to their local location)?

the issue is that the path is like `/media/galleries/304/c65254c2-a583-4951-aa4f-5bf2164aad3e.png` and there is no /media/galleries folder.

**Comment by vhf** [comment]
c317cabbcf02067e9e9c2ba98874530fc1f3514b remark-images-download@2.1.0

**Comment by vhf** [comment]
See https://github.com/zestedesavoir/zmarkdown/blob/a7d8f1c3f6b0bbfbda024cb8cd566e719facb395/packages/zmarkdown/README.md#latex---markdown-to-latex : `opts.local_url_to_local_path`

**Comment by artragis** [comment]
thx.
