### ISSUE TITLE
remark-kbd broken in IE11

### ISSUE THREAD

**Issue by jjenzz** [zestedesavoir/zmarkdown#231]
I'm not sure if the `remark-kbd` package is intended to be run in the browser but we are using it with [React Markdown](https://github.com/rexxars/react-markdown) and having problems in IE11 because `repeat` and `startsWith` are not supported.

Is this something you would consider solving?

**Comment by vhf** [comment]
Thanks @jjenzz , it's definitely something we should fix. I'll take a look at possible solutions later today.

**Comment by vhf** [comment]
@jjenzz published as `remark-kbd@1.0.12`

**Comment by jjenzz** [comment]
Thank you @vhf, that was super quick 🙂
