### ISSUE TITLE
Smileys and underscore

### ISSUE THREAD

**Issue by nils-van-zuijlen** [zestedesavoir/zmarkdown#236]
From zestedesavoir/zds-site#4958 :
> Le smiley >_< n'est pas converti en image sur la beta actuelle (beta de la v27).
> Le bug est présent sur les forums et les commentaires des tutos.
> 
> De plus, il y a un conflit entre l'underscore présents dans ledit smiley et ceux utilisés pour l'emphase.

Le bug n'est pas présent dans les tutos.

**Comment by vhf** [comment]
This smiley is not configured: https://github.com/zestedesavoir/zmarkdown/blob/284b83aa707d4f2891b51ce1b2b70d1df238e291/packages/zmarkdown/config/remark.js#L133-L158

Same goes for other smileys, I know at least of `cthulhu` being missing…
