### ISSUE TITLE
Can't ping a nickname with special characters

### ISSUE THREAD

**Issue by rezemika** [zestedesavoir/zmarkdown#242]
When I ping a nickname with regular characters, all works fine. But when I try to ping a nickname which contain special characters (like accents or greek letters), the nickname is "splitted" and only the first regular characters are used.

![](https://user-images.githubusercontent.com/1690660/42824781-d3f18010-89e0-11e8-99ea-b7484548cefc.png)

**Comment by vhf** [comment]
Please show the corresponding Markdown source.

**Comment by artragis** [comment]
Markdown source (as I don't know how to make a delta, I did not put this one): 

```
ping @rezemika

ping @CielÉtoilé

ping @**CielÉtoilé**
```

What we obtained in html : 

```html
<p>ping <a href="/membres/voir/rezemika/" rel="nofollow" class="ping ping-link">@<span class="ping-username">rezemika</span></a></p>
<p>ping <a href="/membres/voir/Ciel/" rel="nofollow" class="ping ping-link">@<span class="ping-username">Ciel</span></a>Étoilé</p>
<p>ping <a href="/membres/voir/CielÉtoilé/" rel="nofollow" class="ping ping-link">@<span class="ping-username">CielÉtoilé</span></a></p>
```

What we were expecting : 

```html
<p>ping <a href="/membres/voir/rezemika/" rel="nofollow" class="ping ping-link">@<span class="ping-username">rezemika</span></a></p>
<p>ping <a href="/membres/voir/Ciel/" rel="nofollow" class="ping ping-link">@<span class="ping-username">CieÉtoilél</span></a></p>
<p>ping <a href="/membres/voir/CielÉtoilé/" rel="nofollow" class="ping ping-link">@<span class="ping-username">CielÉtoilé</span></a></p>
```

**Comment by vhf** [comment]
`remark-ping` behaves as expected. You can either change its configuration in `zmarkdown` or document the fact that usernames with special characters can be pinged using the `@**` syntax.
