### ISSUE TITLE
Ping and email adress

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#243]
If one writes an email address, like `me@gmail.com`, the `gmail` user is pinged. A solution would be that the ping is activated only if it is preceded by a space or a newline (or nothing if it is the beginning of the md code).

```md
@test? → ping test
I call @test. → ping test
My address is test@test.com → no ping
```

**Comment by vhf** [comment]
`remark-ping` behaves as expected, feel free to change its configuration in `zmarkdown`. For instance by preceding `@` with a [word boundary](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#special-word-boundary) and adding appropriate tests.

**Comment by pierre-24** [comment]
Ok, I open an issue on the other side :)

**Comment by vhf** [comment]
zmarkdown@5.7.0 deployed on the beta server.
