### ISSUE TITLE
autolink with two underscore give italic font

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#245]
with this markdown : 

```
https://developer.mozilla.org/fr/Apps/Game_engines_and_libraries
```
we get
```html
<p><a href="https://developer.mozilla.org/fr/Apps/Game_engines_and_libraries">https://developer.mozilla.org/fr/Apps/Game<em>engines</em>and_libraries</a></p>
```

but we expect : 
```html
<p><a href="https://developer.mozilla.org/fr/Apps/Game_engines_and_libraries">https://developer.mozilla.org/fr/Apps/Game_engines_and_libraries</a></p>
```

**Comment by arobase-che** [comment]
Did the syntax of autolink isn't : 

    <https://developer.mozilla.org/fr/Apps/Game_engines_and_libraries>

 ?

**Comment by artragis** [comment]
Logically, no.

**Comment by vhf** [comment]
@arobase-che That's correct, yes.

My guess is that @artragis meant _autolinks extension_, for which the spec is here: https://github.github.com/gfm/#autolinks-extension-

**Comment by artragis** [comment]
I was refering to the old functionality which was clearly similar to your autolinks-extension document.

I thought we ported this functionnality but removed the "email address transformation" to keep it simpler and make it less buggy than the python-zmarkdown implementation.

**Comment by vhf** [comment]
Let's close this issue since we didn't implement anything like that.

**Comment by artragis** [comment]
I don't understand : we do implement the fact that bare urls are transformed into `<a href` as you can see in the OP.

**Comment by arobase-che** [comment]
> My guess is that @artragis meant autolinks extension, for which the spec is here:
> https://github.github.com/gfm/#autolinks-extension-

Oh ! I wasn't aware that remark support that ! But it does :D 

Ok, so i made a quick test and remark succefully parses autolinks extension syntax. Without the bug that artragis report. But on the ZdS website, zmarkdown parses the syntax as @artragis noticed.

We should investigate because this bug may come from zmarkdown. I'll do it tonight.

**Comment by vhf** [comment]
@artragis We did not implement this, you will not be able to show me code implementing this in the zmarkdown repo. We enabled this behaviour by telling `remark` to use gfm, this is why I referred to the gfm spec in here.

@arobase-che You'd have to check `remark-parse` for the details. I'll disable it for now.

**Comment by arobase-che** [comment]
@artragis: Thanks for the report  :+1: 
I can handle the bug and should fix it  soon.

@vhf: I mean, What is the purpose of putting the attribute 'pedantic' in the config ? Why did we use that attribute ?

**Comment by arobase-che** [comment]
The PR  is ready remarkjs/remark#341

It had to be merged, then once a new version of remark will be published it will be fixed.

**Comment by vhf** [comment]
There seem to be many issues with pedantic mode: https://github.com/remarkjs/remark/pull/344#issuecomment-407403250
> pedantic mode is pretty broken

If it was up to me I'd turn it off, but I guess our users would not be happy with how list behave differently without it.
