### ISSUE TITLE
hl_lines is not supported anymore

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#255]
With zmarkdown, when we want to use hl_lines on source codes, the render to rehype is not properly parsed.

# the markdown

# what we get
```html
        <div class="hljs-code-div"><div class="hljs-line-numbers"><span></span><span></span><span></span><span></span></div><pre><code class="hljs language-python">a = <span class="hljs-number">2</span>
b = a + <span class="hljs-number">5</span>
c = a + b
print(a, b, c)
</code></pre></div>
```
# what we expect : 

something that wraps line 3 (and all lines that are specified) so that css can color it. For example, it can be

```html
        <div class="hljs-code-div"><div class="hljs-line-numbers"><span></span><span></span><span></span><span></span></div><pre><code class="hljs language-python">a = <span class="hljs-number">2</span>
b = a + <span class="hljs-number">5</span>
<span class="hljs-highlight">c = a + b</span>
print(a, b, c)
</code></pre></div>
```

Nota : here are the supported syntax to specify lines : 

```javascript
hl_lines=3 // only line 3 will be highlighted
hl_lines=3,4 // line 3 and line 4
hl_lines=3-8 // line 3 to 8
hl_lines=3,5-8,15 // line 3, lines 5 to 8, line 15 will be highlighted
```

**Comment by Heziode** [comment]
So, line highlight is not implemented and it should not be implemented in highlight.js (see highlightjs/highlight.js#740). Remark use highlight.js for code highlightning.

We need to implement a wrapper to support this feature.

**Comment by TRSasasusu** [comment]
Today, I made a plugin highlighting specific lines.
https://github.com/TRSasasusu/highlightjs-highlight-lines.js

**Comment by artragis** [comment]
Thanks @TRSasasusu. It seems that your plugin requires a browser to run.

**Comment by TRSasasusu** [comment]
Oops, I understood...
So, to make this plugin work in this project, this plugin should work in [lowlight](https://github.com/wooorm/lowlight) used in rehype.

However, I'm sorry, but I'm tied up now, so please wait for dealing with it by me (or please could you do it...?)

**Comment by TitiAlone** [comment]
Since this is now done, I think it can be closed!
