### ISSUE TITLE
zmarkdown: `latex` language not highlighted

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#257]
In pyZmarkdown, when we used

    ```latex
    \cos(n)^2 + \sin(n)^2 = 1
    ```

the code was coloured.

Now, we only support `tex` as language.

Is there a way to add `latex` as alias of `tex` in code highlighting?

**Comment by vhf** [comment]
If we could get access to the `lowlight` instance, e.g. the one exposed here: https://github.com/wooorm/lowlight/blob/master/index.js#L5 , I guess we could create an [alias](https://highlightjs.readthedocs.io/en/latest/api.html?highlight=alias):

```js
low.registerLanguage('latex', require('highlight.js/lib/languages/tex'))
```

I'm not sure `rehype-highlight` exposes its lowlight instance though. One would need to investigate.

**Comment by artragis** [comment]
I opened a pull request on rehype-highlight https://github.com/rehypejs/rehype-highlight/pull/6
