### ISSUE TITLE
Secret blocks: replace default text by title if any

### ISSUE THREAD

**Issue by Ymox** [zestedesavoir/zmarkdown#258]
Hi there!

The possibility to add titles to blocks was added as a feature, title which displays at the top of a block. This behaviour was made the same for the `[[secret]]` block. Yet, the top of the `[[sectet]]` block is not the "hide/show" bar as for now, and this means that the title of the block is secret as well.

I think that the `[[secret]]` block can be improved a little: whenever there's a title provided, it could replace the default text in the "hide/show" interactive bar. Maybe it would need to add or replace the eye by a caret in this case, as the title won't be as self-explanatory as the default text, and some people may overlook the feature.

**Comment by vhf** [comment]
Hi, the code in question here is not part of zmarkdown.
