### ISSUE TITLE
Run zmarkdown client-side

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#259]
The goal is to bundle zmarkdown for client-side use (live preview). Browserify, webpack, we don't have a preference, use whatever works for you.

Some of zmarkdown dependencies would be useless client-side, e.g. `rebber`, `rebber-*`, `remark-image-downloads`, … A way of not bundling them would be not to import them in the entrypoint that will be compiled, I guess.

We want to support a wide range of browsers, no support for IE < 11 though. This means transpiling using babel, including polyfills.

**Comment by Heziode** [comment]
I will start working on it tomorrow.

**Comment by vhf** [comment]
Yep, that was an easy one, I just pushed it because I wanted to fix the zmarkdown README together with it. It's a lot of work so I finally pushed the travis config only.

@Heziode Could you please explain what `check` does? It's mentioned in the readme but I don't understand the text that goes with it.

**Comment by Heziode** [comment]
`check` is an optional function that take in argument a clone of `opts` passing to common. It can be used to allow the use of this plugin depending to the conf (if a some specific values are set to `true, etc.).

But, in hindsight, I think this function are useless…

**Comment by vhf** [comment]
I'll do a PR fixing the doc and removing this

**Comment by Heziode** [comment]
Ok, It's the best to do I think.

**Comment by vhf** [comment]
Great work @Heziode !
