### ISSUE TITLE
[rebber] Wrong TeX with legended code

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#275]
The following code

    ```c
    int main() {
      return 0;
    }
    ```
    Code: un truc minimal(iste)

Generate the following TeX code:

```tex
\begin{codeBlock}[un truc minimal(iste)]{c}
int main() {
  return 0;
}
\end{codeBlock}
```

while it should be `CodeBlock` instead. Note that without legend, it is `CodeBlock` which is generated.

**Comment by vhf** [comment]
Deployed.
