### ISSUE TITLE
[rebber] Caption of code (and image) needs protection for comma and square brackets.

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#276]
A (not so) funny unexpected issue arise when there is a comma in the legend of codes. 

If #275 is fixed, then the following code

    ```c
    int main() {
      return 0;
    }
    ```
    Code: un truc, comme ça

Generates

```tex
\begin{CodeBlock}[un truc, comme ça]{c}
int main() {
  return 0;
}
\end{CodeBlock}
```

while, to avoid issue, it should generates a "protection" for any comma in the caption:

```tex
\begin{CodeBlock}[un truc\protect{,} comme ça]{c}
int main() {
  return 0;
}
\end{CodeBlock}
```

... Otherwise LaTeX thinks it is another option, and fails. It is normally limited to code captions (not table and figures, normally), but if it is easier for you, `\protect{,}` is harmless, so it would work in any caption.

**Comment by vhf** [comment]
Could you please confirm that this is the only character that needs to be protected?

**Comment by pierre-24** [comment]
Or, if you prefer, you don't use that options anymore (they are optional anyway) and systematically use `\captionof{stuff}{The legend}` (`stuff` being `figure`, `table`, `equationfloat` or `listing`). There, nothing more than the usual TeX special characters should be protected. And that would be more consistent (see #278).

As you wish :)

**Comment by vhf** [comment]
What would be `stuff` for `CodeBlock`s?

**Comment by vhf** [comment]
Same question for `Quotation`s?

**Comment by pierre-24** [comment]
`listing` :)

**Comment by pierre-24** [comment]
`Quotation` works differently (like the attention or info box, actually), and do not use a floating environment (thus no `\captionof`). We could do it, though, but would it make sense to give a caption to a quotation ? (especially since it would render like "Quotation 26 -- The author of that quotation").

**Comment by pierre-24** [comment]
What does those thumbs up means ?

1. Yes we would prefer a `\captionof`, or
2. Yes the actual behaviour is fine ? 

It is ambiguous :p

**Comment by vhf** [comment]
"Thanks for the explanation"

I don't know if the current behaviour is fine. Quotes don't have a caption, they have a source. If quote sources are already supported and work well we can simply close this issue.

**Comment by pierre-24** [comment]
Ok :)

**Comment by vhf** [comment]
Deployed.
