### ISSUE TITLE
[rebber] Square bracket is understood as a reference

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#277]
The folllowing piece of code

```
Les bits intéréssants sont les quatres derniers, MUX[0-3] ?
```

Is transformed into 

```tex
Les bits intéréssants sont les quatres derniers, MUX0-3\ref{0-3} ?
```

... And I don't understand why this reference pops out, since the corresponding markdown is correctly generated (without any reference in it).

**Comment by vhf** [comment]
I guess we visit these nodes a bit too early. Thanks for the report!

**Comment by vhf** [comment]
Found it: https://github.com/zestedesavoir/zmarkdown/blob/master/packages/rebber/dist/types/linkReference.js#L3

**Comment by pierre-24** [comment]
Normally, that one is good as well

**Comment by vhf** [comment]
Deployed.
