### ISSUE TITLE
[rebber] Avoid spoiler in spoiler ?

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#280]
After a few hour of trying, I give up: unless someone is a true LaTeX wizard, it is impossible to support spoiler in spoiler (it is already difficult to support spoilers in the first place). The reason is that LaTeX looks for the first `\end{Spoiler}` it can found and stops after that (so imbricated spoilers generate weird behaviour). So, would it be possible to simply render the text of spoiler inside spoilers ?

Eventually, we could provide an environment `SpoilerInSpoiler` so that 

```md
[[s]]
| Another spoiler:
| [[s]]
| | And another:
| | [[s]]
| | | And that's it
```

could be rendered:

```latex
\begin{Spoiler}
Another spoiler:
\begin{SpoilerInSpoiler}
And another:
\begin{SpoilerInSpoiler}
% no need of a SpoilerInSpoilerInSpoiler, otherwise we'll need to define a lots of those!
And that's it
\end{SpoilerInSpoiler} 
\end{SpoilerInSpoiler}
\end{Spoiler}
```

So that we could provide a visual mark that it was a spoiler in a spoiler (in a spoiler). Otherwise, I definitely have no idea on how to support that :s 

Many (many!) thanks in advance :)

**Comment by vhf** [comment]
> So, would it be possible to simply render the text of spoiler inside spoilers ?

We could, I'd like to see some support for this idea before implementing it though. Spoiler have a very special purpose and we need to make sure authors wouldn't mind this.

> `SpoilerInSpoiler`

This shouldn't be harder to implement than the other idea.

**Comment by pierre-24** [comment]
Just to say, this is the piece of markdown that gives me nightmares (from [there](https://zestedesavoir.com/tutoriels/846/pygame-pour-les-zesteurs/1381_a-la-decouverte-de-pygame/5508_la-gestion-des-evenements/#5-15438_entrainons-nous-avec-les-evenements)):

```
[[secret]]
| On avait dit quoi :D ?
| 
| [[secret]]
| | 
| | * À l'initialisation, notre raquette doit avoir une référence vers l'écran, avoir une position de base, et charger son image.
| | 
| | * Quand elle se déplace, on doit être sûre qu'elle ne sort pas de l'écran (jouez avec la méthode `get_size()` de l'image de votre raquette), et la replacer en conséquent.
| | 
| | * Pour les collisions avec la balle, soit vous avez pris de l'avance et lu le chapitre sur les `Rect`, soit vous regardez si la balle est dans la raquette (donc fournissez la position de la balle, et sa taille), méthode un peu plus longue. :)
| | 
| | * Pour ce qui est de la méthode de rendu, c'est super simple, on ne vous en dit pas plus. ;)
```

I can understand the idea, but in this case, it would works as well if the second spoiler is not a spoiler in the PDF. But I'll launch a forum topic ;)

**Comment by TitiAlone** [comment]
Any progress on this front? Are spoilers inside spoilers still a problem? Should we flatten them as it was suggested?

**Comment by pierre-24** [comment]
> Are spoilers inside spoilers still a problem?

Yep, and it will probably always be.

> Should we flatten them as it was suggested?

... Yes please ;)
