### ISSUE TITLE
remark-emoticon/zmarkdown can't start a paragraph by smiley >_<

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#281]
When we write:

```
>_< hello
```

we get

```
<blockquote>
<p>_&#x3C; hello</p>
</blockquote>
```

What is expected is  the same result as 

```
X/ hello
```

i.e

```
<p><img src="/static/smileys/pinch.png" alt="X/" class="smiley"> hello</p>
```

**Comment by vhf** [comment]
You mean at the start of a paragraph, right?

**Comment by artragis** [comment]
Yeah, it's more the paragraph than the sentence here, I edit the OP.

**Comment by Heziode** [comment]
Is it not a "zmarkdwon hack" ? It is an unexpected behavior, like `##Title` that generate title (in old python-zmarkdown).

So this is a bug. We should only allow `> my comment` instead of `>my comment`.

**Comment by Heziode** [comment]
It must be noted that it's still a bit ugly that heading doesn't allow white space but blockquote yes…

**Comment by vhf** [comment]
We don't follow the commonmark spec anyway.

There's a good reason not to support `#hashtag` as headings.

**Comment by Heziode** [comment]
> We don't follow the commonmark spec anyway.

Yes, but remark do.

**Comment by vhf** [comment]
It doesn't work that way. Remark reproduces the original markdown reference implementation, and has config flags to enable commonmark and gfm. Our config disables commonmark and enables gfm.

**Comment by vhf** [comment]
https://github.com/zestedesavoir/zmarkdown/blob/27c98f4ef59f84046c89cd831e9f66439cc17e02/packages/zmarkdown/config/remark.js#L23-L24

**Comment by Heziode** [comment]
gfm also allow `>this`.

**Comment by arobase-che** [comment]
I think that a white-space is needed for ATX headers because one is needed at the end too.

```
# Like this #
```

To keep compatibility we shouldn't allow uncomun syntax. 

> There's a good reason not to support `#hashtag` as headings.

Do you know any other reasons ?

**Comment by Heziode** [comment]
Nope.
So we'll have to find a workaround to support `>_<` at the begining of line.

**Comment by arobase-che** [comment]
By allowing that syntax : 
```
:>_<:
```

Colon it already used to insert emoji. Adding a syntax that allow a optional colon at the begin and end of the emoji to escape it does't seem weird to me.

**Comment by vhf** [comment]
This fix only works if you replace `>_<` with this new syntax, and adding it doesn't make sense to me since we already have a couple of ways of getting this smiley.
