### ISSUE TITLE
[rebber] Get tables with almost the same behavior as in HTML

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#282]
As requested by artragis in https://github.com/zestedesavoir/latex-template/issues/93, here is how to get table that behave almost like their HTML counterparts.

```
C1 | C2 | C3
----|------|-----
short| miiiidle | looooooooooong
``` 

Should be rendered

```latex
\begin{longtabu} spread 0pt {|X[-1]|X[-1]|X[-1]|} \hline
 C1& C2 & C3 \\
\hline
short& miiiidle&looooooooooong\\
\hline
\end{longtabu}
```

notice `spread 0pt`, which gives table a width smaller than the page width if taking that much space is not required.

![screenshot from 2018-09-06 21-05-47](https://user-images.githubusercontent.com/7889675/45179715-95166700-b219-11e8-9c56-cb20fbc38b43.png)

Then `X[-1]` is a (very) special construct that seems to allow columns to takes as much space as they need (but with respect to other columns) but also insert line return if the column is too large. Therefore, this is what we need.

![screenshot from 2018-09-06 21-06-24](https://user-images.githubusercontent.com/7889675/45179826-e7f01e80-b219-11e8-86d5-74fc5da2e39c.png)

If you still prefer that the text is centred (it was the previous behaviour), it is still possible with `X[-1c]`. But personally, I would not recommend it. 

--- 

And if you want to get even closer to the website experience, consider

```latex
\begin{longtabu} spread 0pt {|X[-1]|X[-1]|X[-1]|}
\hline
\rowfont[c]{\bfseries} % first line is with centred-align cells in bold
 C1& C2 & C3 \\
\hline
\rowfont[l]{} % other lines with left-aligned cells. No need to repeat that, once is enough
short & miiiidle & looooooooooong \\
\hline
\end{longtabu}
```

Which gives:

![screenshot from 2018-09-06 21-27-13](https://user-images.githubusercontent.com/7889675/45180443-b4ae8f00-b21b-11e8-8b22-4c933d5a432a.png)

(there is also an option for background color, but do we want that?)

**Comment by vhf** [comment]
Deployed on beta, please check and report back.

**Comment by artragis** [comment]
I confirm from beta that it's ok.
Tables in pdf are however limited. When there are too many columns the render is not readable whatever the options.

perhaps we should try, for another version, to "split" the tables when they have more than 7 or 8 columns.

**Comment by pierre-24** [comment]
It is also possible to put them "sideways" (rotated by 90° on a single page) if you want

**Comment by artragis** [comment]
that would be a nice evolution I think.

**Comment by vhf** [comment]
Good, deploying this to prod then.
