### ISSUE TITLE
remark-download-images: use default black image when 404

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#294]
When we transform our markdown into latex, and some images lead to 404 error, remark-download-images generate a png file but with html content.

Here is an example from @motet-a tutorial: 

```markown
![sprite](https://zestedesavoir.com/static/images/sprite.f651d381c5ba.png)
```
this image is not available. When generating latex, we get this error : 

```json
[
    {
        "column": 1,
        "name": "2142:1-2142:97",
        "line": 2142,
        "reason": "Received HTTP404 for: https://zestedesavoir.com/static/images/sprite.f651d381c5ba.png",
        "ruleId": "//zestedesavoir.com/static/images/sprite.f651d381c5ba.png",
        "fatal": false,
        "stack": "Error: Received HTTP404 for: https://zestedesavoir.com/static/images/sprite.f651d381c5ba.png\n    at Request.request.get.on (/opt/zmd/node_modules/remark-images-download/src/index.js:140:26)\n    at emitOne (events.js:121:20)\n    at Request.emit (events.js:211:7)\n    at Request.onRequestResponse (/opt/zmd/node_modules/request/request.js:1066:10)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)\n    at TLSSocket.socketOnData (_http_client.js:440:20)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at TLSSocket.Readable.push (_stream_readable.js:208:10)\n    at TLSWrap.onread (net.js:607:20)",
        "location": {
            "start": {
                "column": 1,
                "offset": 102942,
                "line": 2142
            },
            "indent": [],
            "end": {
                "column": 97,
                "offset": 103038,
                "line": 2142
            }
        },
        "message": "Received HTTP404 for: https://zestedesavoir.com/static/images/sprite.f651d381c5ba.png",
        "source": "https"
    }
]

```

When image is not properly formatted, latex fails (see https://github.com/zestedesavoir/latex-template/issues/98 ) so I wanted to read the error to generate a fake "black" image to ensure the pdf to be generated.

But as you can see, I have no clue of the generated file name. In this case it was `images/D4AuEmg-ie/vr4WW3-8kIv.png` .

The content is : 
```html
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

# expected

I think many possibilities are acceptable here : 

- in the error object, send the path to bad image file so that I can change it
- automatically create a black square image when status is not 200 OK
- change the image to "default.png" (configurable) when answer is not 200OK

**Comment by vhf** [comment]
@motet-a IIRC there were many things you wanted to refactor in this package, would you want to take a shot at this issue?

**Comment by motet-a** [comment]
@vhf Yes, I have a bunch of improvements and fixes for `remark-images-download` on my box I have to share. I think I will submit a PR soon.

**Comment by motet-a** [comment]
Please take a look at #303.

**Comment by vhf** [comment]
Thanks @motet-a ! 👍

**Comment by artragis** [comment]
How does this PR fix the issue? I don't get the point.

**Comment by motet-a** [comment]
Hey @vhf, @artragis is right: #303 is related but doesn’t fix this issue :upside_down_face:

**Comment by vhf** [comment]
This has been released as:

- remark-images-download@2.9.0
- zmarkdown@6.1.0
