### ISSUE TITLE
rebber: codeblocks in footnotes are not well parsed by latex

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#299]
the following markdown:

```

Pour un tableau[^tableau] : 

[^tableau]:
  `{0}` peut également être utilisé pour un nombre. Toute valeur initialisant une variable simple (pointeur, nombre, ...) peut optionnellement prendre des accolades.

    ```c
    int a = {11};
    float pi = {3.1415926};
    char* s = {"unicorn"};
    ```
  Ce qui caractérise le tableau du coup est surtout le fait d'utiliser des virgules entre les accolades.
```

gives this latex : 
```
Pour un tableau\\textsuperscript{\\ref{footnote:3}}
\footnotetext[3]{\label{footnote:3} \CodeInline{\{0\}} peut également être utilisé pour un nombre. Toute valeur initialisant une variable simple (pointeur, nombre, ...) peut optionnellement prendre des accolades.

\begin{CodeBlock}{c}
int a = {11};
float pi = {3.1415926};
char* s = {"unicorn"};
\end{CodeBlock}

Ce qui caractérise le tableau du coup est surtout le fait d'utiliser des virgules entre les accolades.}
```

the problem is latex can't parse codeblock inside footnote.

We have to send them in appendix like we do for tables.

**Comment by TitiAlone** [comment]
PR was merged, will be in the next release.
