### ISSUE TITLE
implement zds extension: video

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#3]
* https://github.com/zestedesavoir/zmarkdown/blob/master/test/fixtures/zds/extensions/video.txt
* https://github.com/zestedesavoir/zmarkdown/blob/master/test/fixtures/zds/extensions/video_extra.txt

implementation reference:

* https://github.com/zestedesavoir/Python-ZMarkdown/blob/a1481fb4764aafc6051da859ee9280fa16868f65/zmarkdown/extensions/video.py

**Comment by artragis** [comment]
tu peux me l'assigner stp?
