### ISSUE TITLE
Option to have remark-abbr substitute definition for first occurrence.

### ISSUE THREAD

**Issue by roxspring** [zestedesavoir/zmarkdown#304]
In written documents, it's [common](https://blogs.millersville.edu/bduncan/abbreviations-2/) for the first occurrence of an abbreviation to be introduced with the definition first followed by the abbreviation in brackets. It would be great if the `remark-abbr` plugin could optionally do this. e.g.

```markdown
This plugin works on MDAST.

More stuff about MDAST.

*[MDAST]: Markdown Abstract Syntax Tree
```

Would translate to:
```html
<p>This plugin works on Markdown Abstract Syntax Tree (MDAST).</p>

<p>More stuff about <abbr title="Markdown Abstract Syntax Tree">MDAST</abbr>.</p>
```

This would be especially great for workflows where documents are being composed of multiple markdown files and it's not immediately obvious which file will be introducing a given abbreviation first.

**Comment by vhf** [comment]
@roxspring I like this idea. Would you be interested in implementing it?

**Comment by roxspring** [comment]
Sure. Will aim to give it a try soon.

**Comment by artragis** [comment]
Is it ok here?
