### ISSUE TITLE
Drawing a line with +++

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/zmarkdown#309]
It is possible to draw a line using `---` but it isn't with `+++`. It seems that it was possible in the past with zestedesavoir/Python-ZMarkdown. Is it something that could be implemented in zmarkdown or not?

**Comment by vhf** [comment]
It could be but it should not be. One of the goals of zmarkdown was to get closer to a "standard" markdown, we only reimplemented custom syntax for what markdown doesn't already support.

**Comment by Situphen** [comment]
OK, thanks :)
