### ISSUE TITLE
Allow choosing element types for remark-custom-blocks 

### ISSUE THREAD

**Issue by JoshuaWalsh** [zestedesavoir/zmarkdown#310]
## Summary

Currently with custom blocks you can either have your blocks come out as div elements, or as details/summary elements.

It would be nice if we could specify for each block type the element types for the container, title, and contents.
### Basic example

```js
{
  aside: {
    containerElement: "aside",
  },
  collapsible: { // New system would be flexible enough to replace details: true
    containerElement: "details",
    titleElement: "summary",
    contentsElement: "div",
    title: "optional",
  },
}
```

### Motivation

My primary motivation for wanting this feature is to be able to use HTML5 semantic elements such as `<address>`, `<aside>`, etc... from within Markdown.

**Comment by vhf** [comment]
@JoshuaWalsh Sounds like a plan, could you send a PR?

**Comment by artragis** [comment]
Merged and waiting for release @JoshuaWalsh

**Comment by TitiAlone** [comment]
Hi there, the fix was merged and release today as part of `remark-custom-blocks@2.5.0`.
