### ISSUE TITLE
Add Soundcloud

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zmarkdown#314]
Add soundcloud like youtube video : 

    !(https://soundcloud.com/raz3c21/airplane-hayley-ft-b-o-b

HTML : 

     <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/6038702&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>

**Comment by artragis** [comment]
as @TitiAlone merged oEmbed we can close, can't we?

**Comment by vhf** [comment]
I'll close with the package version once released :)

**Comment by vhf** [comment]
remark-iframes@4.0.0 / zmarkdown@6.0.0
