### ISSUE TITLE
remark-grid-tables: problem with accented characters

### ISSUE THREAD

**Issue by benjaminabel** [zestedesavoir/zmarkdown#316]
Hi, and first, thanks for this handy plugin. I found that the parser do not work when there are accented characters on the text(I'm using it from gatsby). For example:

- this works

```md
+-------+--------+------+
| Table | adings | Here |
+=======+========+======+
| celio | column | ning |
+-------+--------+------+
| rows  | normal | cell |
| rows  | normal | cell |
+-------+--------+------+
```
Bit this with just one more accent **not**:

```md
+-------+--------+------+
| Table | adings | Here |
+=======+========+======+
| célio | column | ning |
+-------+--------+------+
| rows  | normal | cell |
| rows  | normal | cell |
+-------+--------+------+
```

**Comment by vhf** [comment]
Minimal reproduction:

```
+---+
| é |
+---+
```
Interestingly enough it works it doesn't work with `è` either but does with `ö`, `ï`…

**Comment by vhf** [comment]
https://www.npmjs.com/package/remark-grid-tables/v/1.5.0

**Comment by vhf** [comment]
I'm not sure this issue can be 100% resolved because fonts and unicode will never 100% match.

On the one hand grid tables are wysiwyg: the visual representation is supposed to be the truth. On the other hand what unicode says about characters width is not always respected by the fonts.

Take for instance a normal width and two full width:
* ø
* †
* €

They'll often seem to have the same width in monospace fonts though:

```
+---+
| ø |
+---+

+----+
| † |
+----+

+----+
| € |
+----+
```

Not much we can do here IMO.

**Comment by benjaminabel** [comment]
Thanks for the fix, however, it stills don't work with my tables that works with the pandoc [extension-grid_tables](http://pandoc.org/MANUAL.html/grid-tables) extension:

```md
+--------------------+---------------------------------+-------------------------------------+
|      Contenus      |       Capacités attendues       |            Commentaires             |
+====================+=================================+=====================================+
| Événements clés de | Situer dans le temps les        | Ces repères historiques seront      |
| l’histoire de      | principaux événements de        | construits au fur et à mesure de la |
| l’informatique     | l’histoire de l’informatique et | présentation des concepts et        |
|                    | leurs protagonistes.            | techniques.                         |
+--------------------+---------------------------------+-------------------------------------+
```

**Comment by vhf** [comment]
Please provide a minimal reproduction.

**Comment by benjaminabel** [comment]
The example is given in the last comment, it is not parsed and appears raw in the generated html.

**Comment by dafanasiev** [comment]
I have same problem with any Cyrillic symbols, and I think that is bug in https://github.com/NXMIX/is-full-width/issues/16

**Comment by vhf** [comment]
> I have same problem with any Cyrillic symbols, and I think that is bug in [NXMIX/is-full-width#16](https://github.com/NXMIX/is-full-width/issues/16)

👍 

I might try using this instead: https://github.com/sindresorhus/is-fullwidth-code-point

**Comment by vhf** [comment]
@dafanasiev Please give [1.6.0](https://www.npmjs.com/package/remark-grid-tables/v/1.6.0) a try

**Comment by dafanasiev** [comment]
> @dafanasiev Please give [1.6.0](https://www.npmjs.com/package/remark-grid-tables/v/1.6.0) a try

Yes, v1.6.0 works as expected for me. Thanks!

**Comment by benjaminabel** [comment]
Yes, v1.6.0 works as expected for me too. Thanks!
