### ISSUE TITLE
zmarkdown : as katex dept is not pinned style can easily be broken

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#323]
We updated zmarkdown in production.
But katex team made a recent upgrade to katex 0.10.1. 
We use 0.10.0 style. As katex dependency management is not strict, we now have a parser that generates not compatible css.

**Comment by vhf** [comment]
> As katex dependency management is not strict, we now have a parser that generates not compatible css.
@artragis I guess you meant HTML, not CSS? Could you please point me to a markup difference between `katex@0.10.0` and `0.10.1`?

**Comment by artragis** [comment]
il fact this was... tricky. katex comes with a js depth which is used in rehype-katex. It also comes with a stylesheet used in zds to display equation with the right fonts & borders. It also comes with the fonts.

If a change is made in HTML generation (for example adding a wrapping span or removing a class) this can lead to a not-well-displayed equation. 

We managed to get the "zmarkdown stylesheet" on zds side.

**Comment by vhf** [comment]
Yeah I got that: https://github.com/zestedesavoir/zmarkdown/pull/325#issuecomment-490605274 , that's not what I'm asking for.

We need examples of math things that generate different HTML depending on whether they go through katex 0.10.0 or katex 0.10.1. As soon as we have this we can leverage the markup for tests.

As I said, I don't think the parser generates any CSS; without markup this we won't be able to get tests that would pass for 0.10.0 while failing for 0.10.1.

**Comment by vhf** [comment]
https://www.npmjs.com/package/zmarkdown/v/5.14.0 released
