### ISSUE TITLE
zmardkown/remark-ping: ping-username class is not added

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#324]
in last version of zmarkdown, when we ping a user the ping-username class is not added on span , current result is : 

```html
<a href="/membres/voir/Situphen/" rel="nofollow" class="ping ping-link">@<span>Situphen</span></a>
```
instead of
```html
<a href="/membres/voir/Situphen/" rel="nofollow" class="ping ping-link">@<span class="ping-username">Situphen</span></a>
```

initial markdown whas `@Situphen` @situphen

**Comment by vhf** [comment]
https://www.npmjs.com/package/zmarkdown/v/5.14.0 released
