### ISSUE TITLE
zmarkdown: sqrt and overarrows not well interpreted

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#326]
When you use zmd to write math some command generate svg and therefore do not display properly due to sanitizer.

Here are the commands known to generate svg:

```
$$
\overrightarrow v 
\overleftrightarrow v
\overleftarrow v 
\sqrt{x}
\overbrace{x + 1}
\color{x}

\overbrace{x+ 1}
\vec{y}
$$
```

Here is the expected visual result : 
![image](https://user-images.githubusercontent.com/1523653/58248109-8813b680-7d5b-11e9-9a38-2dc28240c8e7.png)

**Comment by vhf** [comment]
Fixed in [zmarkdown@5.14.1](https://www.npmjs.com/package/zmarkdown/v/5.14.1).
