### ISSUE TITLE
Demo doesn't work anymore

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#329]
For some reason the demo (<https://zestedesavoir.github.io/zmarkdown/>) started throwing `Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`.

Any idea how to fix it @Heziode ?

**Comment by Heziode** [comment]
Hum… I will check that in few hours.

**Comment by Heziode** [comment]
Ok,

This seems to be related to [core-js](https://github.com/webpack/webpack/issues/4039#issuecomment-492793025).

I will push a fix in few minutes.

**Comment by vhf** [comment]
(This demo is really cool IMO. 👍 )

**Comment by Heziode** [comment]
I use it to convert my university reports from markdown to latex. I have developped my own latex-template for my university reports based on [zestedesavoir/latex-template](https://github.com/zestedesavoir/latex-template) :joy:

**Comment by artragis** [comment]
Can you one day publish your template to show another «working example»

**Comment by Heziode** [comment]
I've been thinking about it for quite some time, but I still haven't taken the time to do it (and to clean the code).
