### ISSUE TITLE
Wrong README title for EPUB

### ISSUE THREAD

**Issue by Vanadiae** [zestedesavoir/zmarkdown#332]
[Here](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/zmarkdown/README.md#epub---markdown-to-html)

> /epub - Markdown to HTML

Being in the EPUB part, this makes no sense because it should be "Markdown to EPUB".

**Comment by TitiAlone** [comment]
I think we are not generating the full EPUB but only the HTML contained in it, so this is quite correct. I'm asking for @vhf advise on this; if it is not correct, I'll correct it with my upcoming PR.

**Comment by vhf** [comment]
An EPUB is an archive containing HTML files (among other things). We are using two endpoints for Markdown to HTML: `/html` and `/epub`. The reason for this is that we want slightly different settings.

Although EPUBs are basically HTML, EPUB readers don't have all the features a browser provides, and EPUBs are supposed to work offline. Take a look here: https://github.com/zestedesavoir/zmarkdown/blob/master/packages/zmarkdown/server/handlers.js#L47-L48
