### ISSUE TITLE
rebber-plugins: No centering inside table

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#335]
LaTeX does not support allignement inside table. Thus,

```
+-------+----------+------+
| Table Headings   | Here |
+=======+==========+======+
| rows  | normal   | cell |
+-------+----------+------+
| multi | ->cells can be  |
| line  | *formatted*     |
|       | **paragraphs**  |
| cells | <-              |
| too   |                 |
+-------+-----------------+
```

Is [actually translated](https://zestedesavoir.github.io/zmarkdown/) into

```latex
\begin{longtabu}{|p{\linewidth / 3}|p{\linewidth / 3}|p{\linewidth / 3}|} \hline
\rowfont[c]{\bfseries}
\multicolumn{2}{|c|}{Table Headings} & Here \\ \hline
\rowfont[c]{\bfseries}
rows & normal & cell \\ \hline
\rowfont[l]{}
multi \par line \par  \par cells \par too & \multicolumn{2}{|c|}{\begin{center} \par cells can be \par \textit{formatted} \par \textbf{paragraphs} \par  \par  \par \end{center}} \\ \hline
\end{longtabu}
```

But `\begin{center}` cannot be inside a table (also, the `{|c|}` of `\multicolumn` already centers the content of the cell).

**Comment by artragis** [comment]
i'll take it

**Comment by Karnaj** [comment]
If we use |p| instead of |c| as `\multicolumn` argument (then just have to compute the width of the multicolumn cell), the code is correct.

```latex
\begin{longtabu}{|p{\dimexpr(\linewidth) / 3}|p{\dimexpr(\linewidth) / 3}|p{\dimexpr(\linewidth) / 3}|} \hline
\rowfont[c]{\bfseries}
\multicolumn{2}{|p{\dimexpr(\linewidth) * 2 / 3}|}{Table Headings} & Here \\ \hline
\rowfont[c]{\bfseries}
rows & normal & cell \\ \hline
\rowfont[l]{}
multi \par line \par  \par cells \par too & \multicolumn{2}{p{\dimexpr(\linewidth) * 2 /3}|}{\begin{center} \par cells can be \par \textit{formatted} \par \textbf{paragraphs} \par  \par  \par \end{center}} \\ \hline
\end{longtabu}
```

**Comment by artragis** [comment]
Is this code generic? I mean, if I put `|p{\dimexpr(\linewidth) / 3}` everywhere, even when there is no align environment, will it work?

**Comment by Karnaj** [comment]
It should. I tried with some examples, and I obtained the expected results.

**Comment by pierre-24** [comment]
Good to know :)

**Comment by artragis** [comment]
petite question, pour `multirow` ça marche? actuellement ça donne ça : 
```js
`\\multirow{${node.data.hProperties.rowspan}}{*}{${baseText}}`
```

**Comment by Karnaj** [comment]
Pour `multirow` il faudrait également utiliser `\parbox`, mais `\par` n'est pas autorisé (ça va, on peut le remplacer par autre chose, ce n'est pas gênant). Mais j'observe un autre souci, il n'adapte pas la taille de la cellule au contenu. On peut régler ce problème en donnant la taille du blanc à laisser en paramètre à `\\`. Ça marche avec `tabular`, pas avec `longtable`... Je vais ouvrir un sujet sur ZdS à propos de ça.

**Comment by vhf** [comment]
rebber-plugins@2.0.0 / zmarkdown@6.0.0

**Comment by artragis** [comment]
@Karnaj for the multirow command we will open a new bug when something happens in prod so that I clearly can understand what is wrong now et what we must do because even in french I did not understand what you expect from zmd.
