### ISSUE TITLE
Support for linenostart

### ISSUE THREAD

**Issue by arobase-che** [zestedesavoir/zmarkdown#340]
Hi \o

`linenostart` was an option used in the previous markdown processor.

Should we implement it ? It's still referenced in the fixtures. [Search for linenostart](https://github.com/zestedesavoir/zmarkdown/search?q=linenostart&unscoped_q=linenostart)

And in the official MD guide ([Rédiger sur ZdS](https://zestedesavoir.com/tutoriels/249/rediger-sur-zds/#d%C3%A9but-de-la-num%C3%A9rotation))

To implement it we need to update remark to version 6. and modify the file [rehype-line-numbers.js](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/zmarkdown/utils/rehype-line-numbers.js) to add something like `style: 'counter-reset: a X;'` where X is based on the attribute `meta` (implemented in version 6 of remark).

💗

**Comment by vhf** [comment]
👍 

See:
> @arobase-che do you want to work on upgrading remark? Anyone else? I probably won't have time but I'd be happy to help.
> 
> We don't need to wait for a remark release containing this bugfix to work on this.
https://github.com/zestedesavoir/zmarkdown/issues/307#issuecomment-510873857

**Comment by artragis** [comment]
to be closed on release, non?

**Comment by TitiAlone** [comment]
I thought this too, but updating only fix for LaTeX.
But with the new version of remark, we are able to use a new syntax for parsing, so this will be fixed soon.

**Comment by arobase-che** [comment]
Still have to write a some code on the side of rehype-line-number I think.
