### ISSUE TITLE
rebber-plugins: grid-tables stringifier replace \n by \par even in \inlineCode

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#352]
# markdown

```
+------+----------------------+
| cell | `code                |
|      | with line break`     |
+------+----------------------+
```

# generated latex

```tex
\begin{longtabu}{|p{\dimexpr(\linewidth) / 2}|p{\dimexpr(\linewidth) / 2}|} \hline
\rowfont[c]{\bfseries}
cell & \CodeInline{code \par with line break} \\ \hline
\end{longtabu}
```

# expected latex

```tex
\begin{longtabu}{|p{\dimexpr(\linewidth) / 2}|p{\dimexpr(\linewidth) / 2}|} \hline
\rowfont[c]{\bfseries}
cell & \CodeInline{code with line break} \\ \hline
\end{longtabu}
```

**Comment by TitiAlone** [comment]
I'm not really sure how to fix that:

- a quick but dirty way would be to do the inverse replacement once again in the code handler of rebber;
- the other one would be to give some kind of priority on handlers;
- the last one I can think of is to roughly match code inside table in the plugin and do not add `\par` in theses case.

I don't really know which one to choose, but I might be missing something.

**Comment by artragis** [comment]
If I remember well the bug comes from a call to `replace(/\n/g, '\\par')` somewhere in the code. a good thing would be to override the `text` node to put the \\par and remove this replace.

**Comment by artragis** [comment]
That's it ! It's here:  https://github.com/zestedesavoir/zmarkdown/blob/master/packages/rebber-plugins/src/type/gridTable.js#L52

In the all() call, you have to override the text handler to add a replace(/\n/g, '\\par')` and remove the global one. Code and inline codes are not basing on text node so the replacement wiil not be applied to them.?

**Comment by artragis** [comment]
I'll take it.

**Comment by vhf** [comment]
This has been released as:

- rebber-plugins@2.1.0
- rebber@3.1.5
- zmarkdown@6.1.0
