### ISSUE TITLE
KaTeX: add mchem

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#359]
[mhchem](https://github.com/KaTeX/KaTeX/tree/master/contrib/mhchem) (an extension to support chemical equation in KaTeX) is supported [since v0.10.1](https://github.com/KaTeX/KaTeX/pull/1436) in KaTeX (the extension is part of the official release, but does not seems activated by default, or at least not on ZdS), and I have to say I would be very happy if we could include it, since I am a huge fan of it. Concerning rebber, we just need to add the "real" `mhchem` package to the template and that's it.

Many thanks in advance :)

**Comment by TitiAlone** [comment]
Depends on [upstream](https://github.com/remarkjs/remark-math/pull/34); we will be able to implement it right after.

**Comment by pierre-24** [comment]
Nice, thanks :)
