### ISSUE TITLE
remark-numbered-footnotes should use `string` identifiers

### ISSUE THREAD

**Issue by wooorm** [zestedesavoir/zmarkdown#361]
https://github.com/zestedesavoir/zmarkdown/blob/a9cba16b5237218a2b59820bda599ee4b0410351/packages/remark-numbered-footnotes/src/index.js#L37

...should be:

```
 node.identifier = String(footnotes[identifier] )
```

...as mdast [requires it to be a string](https://github.com/syntax-tree/mdast#association)!

**Comment by vhf** [comment]
This has been released as:

- remark-numbered-footnotes@1.1.0
- zmarkdown@6.1.0
