### ISSUE TITLE
[rebber-plugins/zmarkdown]emoticon node type is not created

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#364]
In zmarkdown, and all projects that uses remark-emoticon, we add a `emoticon` node type on the MDAST.

Neither `rebber-plugins` nor `zmarkdown` references this type to stringify emoticon, therefore produced texfile/pdf do not embed emoticons.

# expectation

for markdown `:)` the latex endpoint in zmarkdown must render `\smiley{smile.png}`.

**Comment by vhf** [comment]
> for markdown `:)` the latex endpoint in zmarkdown must render `\smiley{smile.png}`.

With our configuration, this would be `\smiley{/static/smileys/smile.png}`, correct?

**Comment by artragis** [comment]
My expected code is the right one, this means we do not correctly configure remark-emoticon for rebber : the emoticon path is defined in `\smileyDict` command and then we give the smiley.

**Comment by vhf** [comment]
Could you please give a link to `\smileyDict`?

**Comment by artragis** [comment]
The current is `/opt/zds/app/dist/smileys` but you really don't need it, you just have to push `\smiley{smile.png}` for example.

**Comment by artragis** [comment]
Thanks a lot
