### ISSUE TITLE
implement zds extension: ping

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#37]
Après une discussion efficace avec @artragis @pierre-24 @gcodeur @AmarOk1412 , voici:

Modification du comportement "actuel":

* la syntaxe est `@oneword` ou `@**pseudo du membre**`, comme représenté par [cette regex](https://github.com/zulip/zulip/blob/ef3069a5d32cc2fdda90248e5ff9ab57a46e1af2/zerver/lib/mention.py#L6)

Pour éviter de fournir un callback, voici l'idée :

* zmd ne retourne pas uniquement l'HTML au backend python, il retourne également la liste des pseudos à potentiellement pinger 
* le backend se charge ensuite de vérifier lesquels sont pingables et de pinger, et donc aussi de respecter l'unicité des pings, respecter les limites de pings / post, etc.

**Comment by sandhose** [comment]
C'est pas cette syntaxe qu'on avait implémenté. D:

https://github.com/zestedesavoir/Python-ZMarkdown/blob/master-zds/zmarkdown/extensions/ping.py#L4-L11

**Comment by vhf** [comment]
Yep @Sandhose c'est normal.
