### ISSUE TITLE
rebber: array improvements

### ISSUE THREAD

**Issue by Karnaj** [zestedesavoir/zmarkdown#374]
The goal is to be able to generate LaTeX code with paragraph in multirow. For that, we have to

- replace `\n` by `\endgraf` ([for now, we replace them by `\par`](https://github.com/zestedesavoir/zmarkdown/blob/a6fc38b3c2a1da34e4916c5ccae601f442396df8/packages/rebber-plugins/src/type/gridTable.js#L54)),
- use `\parbox{\linewidth}{text}` in `\multirow` instead of just `text`,
- use `{\centering text}` and `{\raggedleft text}` instead of `\begin{center} text \end{center}` and `\begin{flushright} text \end{flushright}`.

(We can also replace `p{dim}` by `m{dim}` (see [here](https://tex.stackexchange.com/questions/35293/p-m-and-b-columns-in-tables) for the differences)).

**Comment by artragis** [comment]
Do we need `raggedright` or `raggedleft` to replace `\begin{flushright}`
