### ISSUE TITLE
[rebber] Missing dependencies in package.json

### ISSUE THREAD

**Issue by thomasdondorf** [zestedesavoir/zmarkdown#384]
Just tried to give rebber a try. Looks like it is missing two dependencies in the `package.json` file:

- `clone`
- `trim-lines`

After manually installing them I was able to get it to run. Used version was `5.0.0`.

**Comment by TitiAlone** [comment]
Hello there,

Thanks for reporting the issue, it will be solved in the next release of `rebber` coming soon. Feel free to ask if you have any questions about `rebber` or it's plugins.

**Comment by TitiAlone** [comment]
Released today: `rebber@5.1.0`

**Comment by thomasdondorf** [comment]
Nice, thanks for the fast feedback. Just to let you know: In the end, I didn't end up using `rebber`, mainly because of the missing TypeScript support. Also, I needed something to work directly on the AST.

Looks like a cool project, though :)

**Comment by artragis** [comment]
Do you know how we could support typescript?

**Comment by TitiAlone** [comment]
We need to provide typings I suppose.

**Comment by thomasdondorf** [comment]
@artragis You could either put the type definition files into your project (like [Unified did it](https://github.com/unifiedjs/unified/blob/master/types/index.d.ts)) or provide them via [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Or you switch from JavaScript to TypeScript, but I guess that's not an option ;)

**Comment by LukeCarrier** [comment]
@artragis, @TitiAlone would you accept a PR adding TypeScript declarations for `remark-abbr`?

**Comment by TitiAlone** [comment]
Please do; adding them to only some packages in the repo doesn't really make sense IMO, but I'm interested in seeing how typing declarations work. Do you think adding them to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) would make sense?

**Comment by LukeCarrier** [comment]
Awesome, I'll raise a PR for just one package for now and we can go from there. Thanks!
