### ISSUE TITLE
Problem calculating statistics with some syntaxes.

### ISSUE THREAD

**Issue by firm1** [zestedesavoir/zmarkdown#392]
Zmd version : **8.2.0**

In the title I talk about some syntaxes because I have identified so far only one, but it is difficult to 
say if it is the only one.

Anyway here is an example of what works.

- Asking to parse a normal link without its statistics.

```
curl -H "Content-Type: application/json" -X POST http://localhost:27272/html -d '{"opts": {"stats": false, "disable_ping": true}, "md": "[www.google.com](https://google.fr)"}'
```

**200 OK**

- Ask to parse a link that ends with a dot without its statistics.

```
curl -H "Content-Type: application/json" -X POST http://localhost:27272/html -d '{"opts": {"stats": false, "disable_ping": true}, "md": "[www.google.com](https://google.fr)."}'
```

**200 OK**

- Ask to parse a normal link with its statistics

```
curl -H "Content-Type: application/json" -X POST http://localhost:27272/html -d '{"opts": {"stats": true, "disable_ping": true}, "md": "[www.google.com](https://google.fr)"}'
```

**200 OK**

What doesn't work:

- Asking to parse a link that **ends with a dot** and **with** its statistics

```
curl -H "Content-Type: application/json" -X POST http://localhost:27272/html -d '{"opts": {"stats": true, "disable_ping": true}, "md": "[www.google.com](https://google.fr)."}'
```

**Error 500**

If you need more information, I can provide it.

**Comment by TitiAlone** [comment]
Hi,

I cannot reproduce the error locally, I'm getting a perfectly fine answer (`HTTP 200`), could you provide us with your system information (Node & NPM version, OS & version) and add the logs you get from the server (if any)?

**Comment by firm1** [comment]
Sorry, but I thought I was on version 8.2.0 of zmd, but I'm not, I had an old version obviously.

It's work fine on 8.2.0

Sorry for the inconvenience.
