### ISSUE TITLE
implement zds extension: subscript, superscript

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#4]
* https://github.com/zestedesavoir/zmarkdown/blob/master/test/fixtures/zds/extensions/subsuperscript.txt

reference implementation:

* https://github.com/zestedesavoir/Python-ZMarkdown/blob/a1481fb4764aafc6051da859ee9280fa16868f65/zmarkdown/extensions/subsuperscript.py

**Comment by vhf** [comment]
Cf. `kbd` extension

**Comment by artragis** [comment]
gimme gimme gimme an ext after midnight :p 

Si c'est easy, j'en veux aussi. Bref : tu peux m'assigner.

**Comment by vhf** [comment]
https://github.com/zestedesavoir/zmarkdown/pull/28
