### ISSUE TITLE
rebber: footenotetext cannot be placed everywhere

### ISSUE THREAD

**Issue by pierre-24** [zestedesavoir/zmarkdown#400]
This code actually works after translation in LaTeX:

```md
# The elephant [^a]
[^a]: in the room

!![](https://www.drawingforall.net/wp-content/uploads/2015/03/4-apple-drawing.jpg)
Figure: this is a famous [^b] picture
[^b]: or not
```

This one don't

```md
# The elephant [^ in the room]

!![](https://www.drawingforall.net/wp-content/uploads/2015/03/4-apple-drawing.jpg)
Figure: this is a famous [^ or not] picture
```

-------

I'm a big fan of the `[^ this is a footnote]` feature, which is translated by rebber as

```latex
\textsuperscript{\ref{footnote:2}}\footnotetext[2]{\label{footnote:2} this is a footnote.}
```

Except I just discovered that this is problematic in (at least) two situations: 

+ Inside titles `# the elephant [^ in the room]`
+ In figure (and probably other) captions: `Figure: this is a famous [^ or not] picture`.

Actually, the problem is only the `\footnotetext{}` part (which explains why the first code works and the second don't), so that node should be "delayed" right after the caption/figure in TeX, if possible ;)

 .... except if @Karnaj has an idea on the latex side. The error is, for example,

> Argument of \\@caption has an extra }.

**Comment by TitiAlone** [comment]
Hi,

I'm planning on correcting this in the upcoming version of ZMarkdown, could you please provide the expected result from your example above?

**Comment by TitiAlone** [comment]
Okay, just noticed we do have something to prevent this behavior, but... it seems to be misused for `footnoteDefinition`.

The current system, which I can expand to the test case you give, gives the following result:

```latex
\levelOneTitle{hello\textsuperscript{\ref{footnote:1}}\footnotetext[1]{\label{footnote:1} footnote that i like}\protect}
```

Please note the `\protect` at the end which supposedly solves the bug.

**Comment by Karnaj** [comment]
```latex
\levelOneTitle{hello\textsuperscript{\ref{footnote:1}}\protect\footnotetext[1]{\label{footnote:1} footnote that i like}}
```
(I'm also trying to use `\footnotemark` instead of `\label` and `\ref` (it will permit to have the link to the correct page)).

**Comment by TitiAlone** [comment]
Fixed in upcoming version.
