### ISSUE TITLE
remark-kbd: allow `[[CTRL]]+[[D]]`

### ISSUE THREAD

**Issue by muescha** [zestedesavoir/zmarkdown#405]
### Where

- remark-kbd

### What 

- add option to change fenced chars to `[[` and `]]` like:

```markdown
[[CTRL]]+[[D]]
```

**Comment by TitiAlone** [comment]
Hello there,

thanks for your suggestion.
What you're suggesting is quite easy to implement; maybe you'd be interested in working on it?

**Comment by TitiAlone** [comment]
Your proposal has been implemented; it is now in the codebase but will need to wait for the next version of the plugin coming soon. Will post an update on this issue when it's done.
