### ISSUE TITLE
Add option to choose math syntax 

### ISSUE THREAD

**Issue by Drulac** [zestedesavoir/zmarkdown#408]
Hello :smiley: !

zmarkdown use [rehype-math](https://www.npmjs.com/package/rehype-math) with [rehype-katex](https://www.npmjs.com/package/rehype-katex) to deal with the katex syntax

It could be a great feature to add an option to choose between `katex`, `asciiMath` or `libreOffice like` math syntax
- for me at least, to use zmarkdown in my markdown editor for school
- It could improve usage of zmarkdown in the Node.js/Unified ecosystem

It requires :
- to use [rehype-lo-math](https://github.com/Drulac/rehype-lo-math) for  `libreOffice like` math (_or an other module to deal with asciiMath syntax_) instead of `rehype-katex` here : https://github.com/zestedesavoir/zmarkdown/blob/7d7a9d0dcdc431dd43274f576a903146423f0020/packages/zmarkdown/renderers/html.js#L12
- to replace `katex` sanitize sheme by a `lo-math` sanitize sheme here : https://github.com/zestedesavoir/zmarkdown/blob/5a2c5142c5b5d261af1ede448206b32fe061ba7f/packages/zmarkdown/config/sanitize/index.js#L5
- so there is a need to create a `lo-math` sanitize sheme
- It also require creating new tests

I've hard-coded theses changes on my computer and it works very well

I ask it because it will be really better to set an option, rather than maintening a fork of zmarkdown with theses few changes....

What do you think of this feature ?

--------

I will go to vacation soon, but in August I'll have time to do that if you're ok with it :smile:

**Comment by TitiAlone** [comment]
I do not think we need any changes, what you want to do is already possible; you need to:

1. require the "common" module instead of the default provided one;
2. disable the KaTeX plugin;
3. load your custom plugin;
4. create a custom parser using the ZMarkdown API.

It should look something like this, altough I was not able to run your plugin (missing mathjax, and then missing some obscure module):

```js
const clone = require("clone");
// 1. Require the "common" module
const zmarkdown = require("zmarkdown/common");

// Clone our configuration (or use your own)
const yourMdastConfig = clone(require("zmarkdown/config/mdast"));
const yourHtmlConfig = clone(require("zmarkdown/config/html"));

// 2. Disable the default KaTeX renderer
yourHtmlConfig.disableTokenizers = {
	internal: ["katex"],
};

// 3. Use your plugin instead
yourHtmlConfig.extraPlugins = {
	"lo-math": require("rehype-lo-math"),
};

// 4. Create a parser and use it
const parser = zmarkdown("html", yourMdastConfig, yourHtmlConfig);

parser("L = {1} over {2} * rho v^2 S C_L")
	.then(console.log);
```

**Comment by Drulac** [comment]
thanks for this reply :smiley: !

from what I understand, I think it will be more like that ?
```js
// 3. Use your plugin instead
yourHtmlConfig.extraPlugins = {
	"katex": require("rehype-lo-math"),
};
```
Indeed it don't work too

I will play a bit with this code, trying to make it work :smiley:

**Comment by TitiAlone** [comment]
> from what I understand, I think it will be more like that ?

You can put the name you want, it doesn't matter.

**Comment by Drulac** [comment]
after a more deep look, I've found why it was not working : you've just forgot the `$` at start and at end of the math expression
```js
parser('$L = {1} over {2} * rho v^2 S C_L$')
	.then(console.log);
```
with this your code work well :smiley: ! thanks a lot :smiley: !
