### ISSUE TITLE
zmarkdown: inverting line number of a range causes a fatal error

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#414]
The bug only appears with current zmarkdown configuration, you just have to start the server and send provided markdown

# The minimal code

```
```php hl_lines="3-01"
<?php

namespace App\Validator;
```

# observed behaviour

error is raised in `zmarkdown/utils/code-handler.js` at line 70
```
RangeError

Invalid array length
```

# desired behaviour

two possible behaviour : 

- if left limit is greater than right limit, do nothing, 
- swap the range limits if they are inverted

**Comment by TitiAlone** [comment]
I saw this error, and I think it's obviously a misuse of the plugin, but anyway adding a check is no big deal.

**Comment by artragis** [comment]
It's juste we don't want the parsing to be stopped when users makes a typo.
