### ISSUE TITLE
Ability to add comments

### ISSUE THREAD

**Issue by Nek-** [zestedesavoir/zmarkdown#439]
Github markdown supports comments:

```markdown
<!-- This is a comment -->
```

Having it in zmarkdown would be actually awesome for the edition of huge content.

**Comment by arobase-che** [comment]
You should already be able to use it.

Using a syntax like :

```markdown
<--COMMENTS This a little comment. COMMENTS-->
```

**Comment by Nek-** [comment]
En effet
