### ISSUE TITLE
Not able to recreate a table with remark-grid-tables

### ISSUE THREAD

**Issue by sk8Guerra** [zestedesavoir/zmarkdown#444]
I'm trying to create a table like this:

<img width="198" alt="Screen Shot 2021-08-14 at 12 24 23" src="https://user-images.githubusercontent.com/18681676/129456770-b8988f18-2bfc-41c2-80e6-c8807b42855e.png">

This way:

<img width="158" alt="Screen Shot 2021-08-14 at 12 24 44" src="https://user-images.githubusercontent.com/18681676/129456777-48932280-22cf-49cf-b51d-005306f4b62c.png">

But the desired result is not correct:

<img width="240" alt="Screen Shot 2021-08-14 at 12 25 21" src="https://user-images.githubusercontent.com/18681676/129456801-227d507d-bf10-4931-bbeb-3f0bae4c7eb7.png">

Because there is still a division in the last cell.

Is this supported?

**Comment by artragis** [comment]
I don't think it's possible de produce such a table with HTML. I can't even produce them with Libre Office.

**Comment by sk8Guerra** [comment]
Hmm, you're right. Google Sheets doesn't allow it either. 🤔

Do you think it is because HTML doesn't support it?

**Comment by StaloneLab** [comment]
I just tested it in HTML, and indeed it doesn't seem to be supported. The code that should generated your result would be:

```html
<table>
  <tr>
    <td>1</td>
  </tr>
  
  <tr>
    <td colspan="2" rowspan="2">3</td>
  </tr>
</table>
```

Which gives nothing good at all, you can see the result on the image below:

![Capture du 2021-08-20 22-09-42](https://user-images.githubusercontent.com/6739422/130288331-a466e864-859f-473d-bc03-fa9291d604a6.png)

Hence I don't think we can handle it properly in the plugin, sorry.
