### ISSUE TITLE
remark-align@1.2.14 TypeError: Cannot set properties of undefined (setting 'alignBlocks')

### ISSUE THREAD

**Issue by M1seRy** [zestedesavoir/zmarkdown#446]
hi，I use remark-align@1.2.14 in [bytemd](https://github.com/bytedance/bytemd) trying to test markdown text align in remark processing, 

here's the codesandbox demo link:  https://codesandbox.io/s/bytemd-remark-align-demo-lgvpb ,

it goes to a error: 
![image](https://user-images.githubusercontent.com/10118666/132671912-fd893843-1dee-4a65-80de-8c041dbe001e.png)

**Comment by StaloneLab** [comment]
What version of remark are you using? A mention is included in the README:

> Currently, all the plugins provided only work for remark versions lesser than 13.0.0.

If you are using a version greater or equal to 13.0.0, then you'll need to wait for #416

**Comment by M1seRy** [comment]
Hi @StaloneLab thanks for your prompt reply ~
not a greater version, using "remark-parse": "^9.0.0", "remark-parse": "^9.0.0","remark-rehype": "^8.1.0",  "unified": "^9.2.2"

**Comment by StaloneLab** [comment]
This is a greater version unfortunately. I was referring to the version of `remark`, but `remark-parse` has different versioning. See if you can make it work by downgrading `remark-parse` to 8.x. You might need to downgrade some other dependencies to have them work with it, for instance `remark-rehype` should stay in version 7.x.

If you cannot downgrade, then please refer to the issue linked above.
