### ISSUE TITLE
Cannot read properties of undefined (reading 'blockTokenizers')

### ISSUE THREAD

**Issue by polyamakov** [zestedesavoir/zmarkdown#470]
Hi! I have problems, I have to update "react-markdown" at least to "^7.1.1", But when i do it remarkDisableTokenizers is broken. 
 
`<ReactMarkdown remarkPlugins={[remark, [remarkDisableTokenizers, { block: ['setextHeading'] }]]} ... />`

"react-markdown": "^7.1.1",
"remark-disable-tokenizers": "^1.1.0",

<img width="865" alt="image" src="https://user-images.githubusercontent.com/43311887/187137606-79916dad-6c52-4e69-aaa3-0e8254ffe209.png">

Could you help me please? no one on the whole internet has come across this problem

**Comment by StaloneLab** [comment]
Hello, I think you have the problem mentioned in issue #416 : your remark version does not match the version needed by our plugins. To be more specific, we state that:

> Currently, all the plugins provided only work for remark versions lesser than 13.0.0.

If you are using a version *greater than or equal to* 13.0.0, then you'll need to wait (probably for a long time) for the plugin to be migrated or use the tricks mentioned here: https://github.com/zestedesavoir/zmarkdown/issues/416#issuecomment-982484060
