### ISSUE TITLE
Zmd generates an ordered list in a case it shouldn't

### ISSUE THREAD

**Issue by philippemilink** [zestedesavoir/zmarkdown#495]
With the following Markdown code:
```md
These are the first three numbers:
- 1;
- 2;
- 3.

See?
```
zmd understands the `3.` is the third element of an ordered list, and the `3.` is shifted in the rendered HTML:

![screenshot](https://github.com/zestedesavoir/zmarkdown/assets/5911232/011ae4ff-8625-4fc7-b2ad-69925f2c4f9e)

**Comment by arobase-che** [comment]
Non, pour moi c'est un comportement normal.  
Si vous voulez un nombre échappez juste le point.

```md
- 1;
- 2;
- 3.
```

**Comment by StaloneLab** [comment]
I agree with @arobase-che , not a Markdown bug, results of the combination of GFM examples 262 ("A list may start or end with an empty list item") and 276 ("A list may be the first block in a list item"). Escaping is the solution to use if the behavior you are referring to is needed.
