### ISSUE TITLE
zmarkdown: all tests skipped because of typography

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#51]
* Skipped here: https://github.com/zestedesavoir/zmarkdown/blob/29746b200cf10d50ea76c8dbb6533a2eac6affad/packages/zmarkdown/test/test.js#L21
* We'll need to think about the best way of reenabling some of them
* The approach of enabling all plugins that are necessary for zmarkdown to replace python-zmarkdown is incompatible with python-zmarkdown test suite because it was selectively enabling/disabling plugins -- not all of them were applied to all fixtures for the tests to pass

**Comment by artragis** [comment]
Perhaps some fixtures were juste badly designed?

**Comment by vhf** [comment]
They were indeed, but the bigger issue is that fixtures were tested with a weird configurable combination of plugins.

Running all our plugins against the former fixtures won't ever work for this reason.

Example: Their typographic extension wasn't activated for most fixtures tests, so most of the tests will fail because our typographic extension will replace quotes and fail for that reason.

**Comment by artragis** [comment]
I will check it when I have time.

Do you want to get the test like they were (i.e all fixtures to test the zmarkdown software) or keep a "unit test" philosophy were each test is here for one package only and just keep the "demonstration tutorial" to test zmarkdown?

**Comment by vhf** [comment]
All zmarkdown tests have been unskipped.

We'll add a suite of integration tests to zmarkdown later on.
