### ISSUE TITLE
Table does not have caption

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zmarkdown#67]
Like #66 we need a plugin to embed caption for tables

Example of code:

```markdown
a | b
----|----
c | d
Table: dummy

+-----+-----+
|  a  |  b  |
+-----+-----+
|  c  |  d  |
+-----+-----+
Table: dummy
```

**Comment by artragis** [comment]
They have it, only rebber needs a full plugin for that but it is not so easy.

**Comment by AmarOk1412** [comment]
I reopen because of:
```
+-----+-----+
|  a  |  b  |
+-----+-----+
|  c  |  d  |
+-----+-----+
Table: dummy
```

**Comment by vhf** [comment]
Please explain what's wrong :)

**Comment by AmarOk1412** [comment]
Yeap @vhf I know, but I didn't know what's wrong, but I think I understand now!

@artragis https://github.com/zestedesavoir/zmarkdown/blob/master/packages/remark-captions/src/index.js#L17 (`Object.keys(legendBlock).forEach(nodeType =>
visit(tree, nodeType, externLegendVisitorCreator(blocks)))`)

The plugin only visit nodes in `legendBlock`, not in `blocks`. New nodes in `blocks` is ignored. I think we just have to replace `legendBlock` by `blocks` and add a new test (and it will work). If you want to correct this (or I can do this after the ping plugin).

**Comment by artragis** [comment]
Ok thank you. I fix it quickly.
