### ISSUE TITLE
Blockquotes, after the block.

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zmarkdown#77]
I think there is a bug here:

![2017-06-15-19 16 13-screenshot](https://user-images.githubusercontent.com/1888628/27205499-35271400-51ff-11e7-8983-3a10704ca806.png)

`After the quote` should be... after the quote.

**Comment by vhf** [comment]
It doesn't look weird to me, could you please double check what the current zds markdown implementation does and whether this behavior matches?

**Comment by AmarOk1412** [comment]
Ohh indeed, I've got the same result on https://zestedesavoir.com
