### ISSUE TITLE
typographic-guillemets <<a>>

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zmarkdown#80]
`<<a>>` must be replaced by `«a»`.

**Comment by AmarOk1412** [comment]
Note: it's because <a> is transformed by rehype

**Comment by vhf** [comment]
Textr runs before any remark plugin which in turn run before rehype and its plug-ins. Could you elaborate what you think the issue is?

**Comment by AmarOk1412** [comment]
In fact. Try this:

```js
 AmarOk@tars2  ~/Projets/Web/zmarkdown/packages/zmarkdown   issue_80 ●  cat remark-textr.js
const visit = require('unist-util-visit')
const textr = require('textr')

module.exports = plugin

function plugin ({ plugins = [], options = {} } = {}) {
  let fn
  return transformer

  function transformer (tree) {
    fn = plugins.reduce(
      (processor, p) => processor.use(typeof p === 'string' ? require(p) : p),
      textr(options)
    )
    console.log(tree)

    visit(tree, 'text', visitor)
  }
  function visitor (node) {
    node.value = fn(node.value)
  }
}
```

And try (on the demo page) `<<a>`
The tree visited by `remark-textr.js` is:

```
root[1] (1:1-1:5, 0-4)
└─ paragraph[2] (1:1-1:5, 0-4)
   ├─ text: "<" (1:1-1:2, 0-1)
   └─ html: "<a>" (1:2-1:5, 1-4)
```

And typographic plugins are executed on text nodes. So typographic-guillemets will not see `<a>`.

**Comment by vhf** [comment]
Thanks!

remark-textr is the first visitor to run after remark-parse, the issue is that remark-parse will turn `<(.*)>` into an `html` type node: https://github.com/wooorm/remark/blob/master/packages/remark-parse/lib/locate/tag.js

I don't have a solution at the moment.
