### ISSUE TITLE
Titles needs too many spaces

### ISSUE THREAD

**Issue by artragis** [zestedesavoir/zmarkdown#90]
With this code:

```markdown
# Image

## Simple

![alt](https://zestedesavoir.com/media/galleries/4092/5a95eebb-6768-4727-952a-927bd69352a1.jpg.96x96_q95_crop.jpg)

## figured

![alt](https://zestedesavoir.com/media/galleries/4092/5a95eebb-6768-4727-952a-927bd69352a1.jpg.96x96_q95_crop.jpg)
Figure: figure
```

the `## figured` is not interpreted as title

![capture d ecran 2017-06-22 a 13 49 36](https://user-images.githubusercontent.com/1523653/27432723-a68e2c6c-5751-11e7-819c-7f1049e8aa44.png)

**Comment by vhf** [comment]
I wasn't able to reproduce this bug. Could you help me reproduce it?

**Comment by AmarOk1412** [comment]
mwahahaha @artragis I know how to reproduce. In `img.fixture.md`, `##` is followed by a nbsp, so it's not a bug. You just have to replace the nbsp by a space and it will work ;)
