### ISSUE TITLE
remark-captions: decide how img/Figure should work

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zmarkdown#95]
I'm not sure what's the desired behaviour for images with legends.

What I understand by reverse engineering zmd is:

```md
foo

![]()
Figure: 1 this is parsed as legend

baz

![]()
aFigure: 2 this text doesn't show up, img is wrapped in figure

![alt 2b](https://zestedesavoir.com/static/images/home-clem.4a2f792744c9.png)
this text doesn't show up, img is wrapped in figure, legend is "alt 2b"

foo
![]()
Figure: 3 this is displayed as text

![]()
Figure: 4 this is a legend, remainder of the paragraph goes into
the
legend
```

* I guess the main goal is to only parse a legend when the paragraph starts with an img.
* I'd vote for eliminating the behaviour illustrated by `2` and `4`
* Regarding `2b`, I would also drop support but keep the idea of using alt as legend if the paragraph only consists of an img. `2b` would be parsed as inline img with text following the image.

**Comment by AmarOk1412** [comment]
+ I'd vote for eliminating the behaviour illustrated by `2` -> +1 (and +1 for eliminating `2b`)

+ Why do you want to eliminate `4`?

I agree with the rest.

**Comment by artragis** [comment]
2b should be eliminated as it is not logical

3) should be "fixed" : as we force the Figure token, we should put the image inside a figure

**Comment by vhf** [comment]
Ok, let's keep `4` and fix `3`.
